<?php

return [
    /* kathmandu - 23 */
    'ktm-23-kumari-che'           => 'ktm23kumarien',
    'ktm-23-kumari-che-np'        => 'ktm23kumarinp',
    'ktm-23-johche-bahah'         => 'ktm23johchebahahen',
    'ktm-23-johche-bahah-np'      => 'ktm23johchebahahnp',
    'ktm-23-bikahamh-bahah'       => 'ktm23bikahamhbahahen',
    'ktm-23-bikahamh-bahah-np'    => 'ktm23bikahamhbahahnp',
    'ktm-23-baniya-bahah'         => 'ktm23baniyabahahen',
    'ktm-23-baniya-bahah-np'      => 'ktm23baniyabahahnp',
    'ktm-23-punche-bahah'         => 'ktm23punchebahahen',
    'ktm-23-punche-bahah-np'      => 'ktm23punchebahahnp',
    'ktm-23-ganca-bahah'          => 'ktm23gancabahahen',
    'ktm-23-ganca-bahah-np'       => 'ktm23gancabahahnp',
    'ktm-23-gancanani-bahah'      => 'ktm23gancananibahahen',
    'ktm-23-gancanani-bahah-np'   => 'ktm23gancananibahahnp',
    'ktm-23-mimnami-bahah'        => 'ktm23mimnamibahahen',
    'ktm-23-mimnami-bahah-np'     => 'ktm23mimnamibahahnp',
    'ktm-23-bhon-bahah'           => 'ktm23bhonbahahen',
    'ktm-23-bhon-bahah-np'        => 'ktm23bhonbahahnp',
    'ktm-23-baku-bahah'           => 'ktm23bakubahahen',
    'ktm-23-baku-bahah-np'        => 'ktm23bakubahahnp',
    'ktm-23-thana-bahah'          => 'ktm23thanabahahen',
    'ktm-23-thana-bahah-np'       => 'ktm23thanabahahnp',
    'ktm-23-nhuche-bahah'         => 'ktm23nhuchebahahen',
    'ktm-23-nhuche-bahah-np'      => 'ktm23nhuchebahahnp',
    'ktm-23-tvahkeba-bahah'       => 'ktm23tvahkebabahahen',
    'ktm-23-tvahkeba-bahah-np'    => 'ktm23tvahkebabahahnp',
    'ktm-23-pahkhahche-bahah'     => 'ktm23pahkhahchebahahen',
    'ktm-23-pahkhahche-bahah-np'  => 'ktm23pahkhahchebahahnp',
    'ktm-23-yutanani-bahah'       => 'ktm23yutananibahahen',
    'ktm-23-yutanani-bahah-np'    => 'ktm23yutananibahahnp',
    'ktm-23-gabhah-bahah'         => 'ktm23gabhahbahahen',
    'ktm-23-gabhah-bahah-np'      => 'ktm23gabhahbahahnp',
    'ktm-23-nabahi'               => 'ktm23nabahien',
    'ktm-23-nabahi-np'            => 'ktm23nabahinp',
    'ktm-23-shikhamu-bahah'       => 'ktm23shikhamubahahen',
    'ktm-23-shikhamu-bahah-np'    => 'ktm23shikhamubahahnp',

    /* kathmandu - 22 ward */
    'ktm-22-wotu-bhadrakali-nb'     => 'ktm22wotubhadrakalibnb',
    'ktm-22-wotu-bhadrakali-np'     => 'ktm22wotubhadrakalinp',
    'ktm-22-swet-siddhibinayak-nb'  => 'ktm22swetsiddhibinayaknb',
    'ktm-22-swet-siddhibinayak-np'  => 'ktm22swetsiddhibinayaknp',
    'ktm-22-ranamukteshwor-nb'      => 'ktm22ranamukteshwornb',
    'ktm-22-ranamukteshwor-np'      => 'ktm22ranamukteshwornp',
    'ktm-22-lumadhi-ajima-nb'       => 'ktm22lumadhiajimanb',
    'ktm-22-lumadhi-ajima-np'       => 'ktm22lumadhiajimanp',
    'ktm-22-sabal-bahaa-nb'         => 'ktm22sabalbahahnb',
    'ktm-22-sabal-bahaa-np'         => 'ktm22sabalbahahnp',
    'ktm-22-chidha-bahaa-nb'        => 'ktm22chidhabahahnb',
    'ktm-22-chidha-bahaa-np'        => 'ktm22chidhabahahnp',
    'ktm-22-pinche-bahaa-nb'        => 'ktm22pinchebahahnb',
    'ktm-22-pinche-bahaa-np'        => 'ktm22pinchebahahnp',
    'ktm-22-paalhaa-nb'             => 'ktm22paalhaanb',
    'ktm-22-paalhaa-np'             => 'ktm22paalhaanp',
    'ktm-22-pyukha-bahaa-nb'        => 'ktm22pyukhabahaanb',
    'ktm-22-pyukha-bahaa-np'        => 'ktm22pyukhabahaanp',
    'ktm-22-mahankadyo-nb'          => 'ktm22mahankadyonb',
    'ktm-22-mahankadyo-np'          => 'ktm22mahankadyonp',
    'ktm-22-tebaha-nb'              => 'ktm22tebahanb',
    'ktm-22-tebaha-np'              => 'ktm22tebahanp',
    'ktm-22-ganamahabihar-nb'       => 'ktm22ganamahabiharnb',
    'ktm-22-ganamahabihar-np'       => 'ktm22ganamahabiharnp',
    'ktm-22-mu-bahaa-nb'            => 'ktm22mubahaanb',
    'ktm-22-mu-bahaa-np'            => 'ktm22mubahaanp',

    /* Changunarayan - 4 ward */
    'bkt-4-changunarayan'               => 'chn4changunarayanen',
    'bkt-4-changunarayan-np'            => 'chn4changunarayannp',
    'bkt-4-kileshwor-mahadev-temple'    => 'chn4kileshwormahadeven',
    'bkt-4-kileshwor-mahadev-temple-np' => 'chn4kileshwormahadevenp',
    'bkt-4-chhinnamasta-temple'         => 'chn4chhinnamastaen',
    'bkt-4-chhinnamasta-temple-np'      => 'chn4chhinnamastanp',
    'bkt-4-garud-narayan-icon'          => 'chn4garudnarayaniconen',
    'bkt-4-garud-narayan-icon-np'       => 'chn4garudnarayaniconnp',
    'bkt-4-historical-column-of-mandev' => 'chn4historicalcolumnmandeven',
    'bkt-4-historical-column-mandev-np' => 'chn4historicalcolumnmandevnp',

    /* Lubhu Mahalaxmi Nagarpalika - 6,7,8 ward */
    'mm-6-nasadyo-balkumari-en' => 'mm6nasadyobalkumarien',
    'mm-6-nasadyo-balkumari-np' => 'mm6nasadyobalkumarinp',
    'mm-6-mahankal-bhairab-en'  => 'mm6mahankalbhairaben',
    'mm-6-mahankal-bhairab-np'  => 'mm6mahankalbhairabnp',
    'mm-7-changthali-en'        => 'mm7changthalien',
    'mm-7-changthali-np'        => 'mm7changthalinp',
    'mm-6-ganesh-nen'           => 'mm6ganeshnen',
    'mm-6-ganesh-np'            => 'mm6ganeshnp',
    'mm-8-lubhu-mahalaxmi-en'   => 'mm8lubhumahalaxmien',
    'mm-8-lubhu-mahalaxmi-np'   => 'mm8lubhumahalaxminp',


];
